### ISSUE TITLE
Making items use actual Rarities rather than arbitrary numbering

### ISSUE THREAD

**Issue by ScuffedNewt** [corowne/lorekeeper#1113]
as the title states

**Comment by ScuffedNewt** [comment]
examples can be seen on item variants and a few other extensions that benefit from the use of rarities, plus I think logically it makes most sense for rarities to be consistent across the board

**Comment by itinerare** [comment]
On the other hand, sites may not use the same rarity systems between characters/traits and items-- so any solution for this needs to accommodate that possibility as well as allow conditional loot tables to work (i.e. still correlate rarities to numeric values).

**Comment by ScuffedNewt** [comment]
I think this should be solved on the rarity side, though, by making subcategories or divisions rather than on the item side. It is disruptive to the flow of how other things work especially considering most extensions use rarities as-is rather than creating a new system which ideally is how it should be

**Comment by itinerare** [comment]
Oh, I'm not arguing for any particular resolution-- I'm just saying that the kind of functionality that's presently there needs to be maintained one way or another. Making the rarity system more robust feels like a reasonable way about it, though.

**Comment by ScuffedNewt** [comment]
do you prefer if the rarity subcategories go in a new PR or as a separate issue to be discussed on how best to approach it?

**Comment by itinerare** [comment]
Just directly to new PR might be best, unless you have specific questions regarding the implementation?

**Comment by ScuffedNewt** [comment]
not really honestly, perhaps the only thing would be having varying searches based on the categorisations
I'll mull it over since I won't get to it for a few hours for sure anyway

**Comment by itinerare** [comment]
Yeah, very fair. Sounds good, anyhow
