### ISSUE TITLE
Encyclopedia displaying duplicates of items and traits

### ISSUE THREAD

**Issue by SpeedyD** [corowne/lorekeeper#210]
### Bug as reported:
(Bug found on multiple Lorekeeper sites, ranging from an older pre-2.0.0 dev branch up to the latest version.)

**URL of page:** `<siteurl>/world/items?page=<number>`, `<siteurl>/world/traits?page=<number>` and (if the extension is installed) `<siteurl>/world/awards?page=<number>`
**Description of bug:** The Encyclopedia seems to be displaying duplicates of items and traits, on numerous occasions. The more items/traits a site has, the more likely duplication happens in the Encyclopedia. I have extensively checked whether or not the items/traits are actually doubled, and they are not. Item/Trait ID is the same as the original for duplicates.
**How was the bug caused (exact steps to reproduce):**
Simply head for the encyclopedia, click All Items or All Traits and look through carefully. It happens often on page 2 and 3, but some repeat later pages too. Sometimes, the order of the items/traits is different, for some reason.
This also occurs with awards in the Encyclopedia, from the [Awards Extension](http://wiki.lorekeeper.me/index.php?title=Extensions:Awards).
### Further details
I have noticed that sites with a low amount of items/traits are less likely to have duplicates if only for the sole reason that there's less pages in which this can happen.
If you sort them alphabetically, the duplicates seem to disappear; but the page count stays the same, and as the item count on the last page is also the same number, it appears that the duplicates are actually obfuscating actual items in the list.. Especially since the item per page count is the same as well.
Further research confirmed this; on some sites items that should appear in the list do not appear at all, not even later pages, until we sort by alphabet or newest/oldest first. It only happens when you Sort by Category, as is the default, so I presume it happens in the `sortCategory()` function. Unfortunately, I have no idea how to fix this.

**ADDITION:**
Tested other sorting methods and even tested the Awards extensions. Text above has been edited accordingly.

**Comment by itinerare** [comment]
I've put a potential fix for this on my main branch courtesy of a method introduced in Laravel 6, iirc. Will PR at or before when 2.1 approaches readiness but would appreciate testing in the interim if it's convenient to do so, esp since it's the only significant change on the branch atm.
