### ISSUE TITLE
Users with long usernames cause the sidebar to partially disappear

### ISSUE THREAD

**Issue by SpeedyD** [corowne/lorekeeper#38]
### Bug as reported:

**URL of page:** All user pages
**Description of bug:** Sidebar on the left gets hidden behind site content
**How was the bug caused (exact steps to reproduce):**
Make your browser thinner on the userpage of a user with a long name.

### Further details

Users with long names causes the links in the sidebar on the left to get hidden behind site content, if the browser isn't wide enough. Considering not everyone uses full HD resolutions on their screen, their browser might not ever get wide enough.

It's not a major bug as the mobile size picks up the pace in general, but it's still a problem that happens in core Lorekeeper.

**Comment by SpeedyD** [comment]
Realization was made that this also occurs on _character pages_ when the _character_ has a long name.

**Comment by SpeedyD** [comment]
Minor suggestion for fix?

https://stackoverflow.com/questions/15012712/truncate-string-in-laravel-blade-templates/24902688#24902688

Truncating names. It's not important to have the full name of characters or users in the sidebar anyway, especially since they're displayed on the pages themselves, too.

**Comment by itinerare** [comment]
Ah, yeah, it'd be pretty easy to truncate especially long names/that'd be a decent solution... probably just needs some fiddling as to precisely how long it's allowed to be before it truncates, esp w regards to figuring out something that's a generally applicable value.

**Comment by SpeedyD** [comment]
On core Lorekeeper, the longest term on both character pages and userpages is 'OWNERSHIP HISTORY'. That's 17 characters.
With a long name, when the browser is smallest, it seems about 9-11 characters are visible..

Considering that the menu items get new-lined if they're squished, the issue is solely the breaking of the column when the name is long..

If there is a way to see browser width in Laravel, I'd suggest either variable widths, but at the purest, most basic form, I'd suggest using around 10 as a maximum.

**Comment by itinerare** [comment]
I was actually looking into determining viewport width for something else.... if I recall correctly, that is a Hassle, so 10 just a hard cap is probably the idea.

**Comment by SpeedyD** [comment]
For characters, (`resources\views\character\_sidebar.blade.php`) I think it's easier to just replace the `{{ $character->fullName }}` on line 2 with `{{ $character->slug }}`. The slug scrunches up automatically because of the hyphens, so it really just depends on the given name whether it might mess things up or not. (Not showing the name doesn't matter for the sidebar anyway..)

As for the users, (`resources\views\user\_sidebar.blade.php`) probably replace the `{{ $user->name }}` on line 2 with `{{ \Illuminate\Support\Str::limit($user->name, 10, $end='...') }}` and hopefully that should do it..?

Sorry for not just doing it and sending a PR, I am currently not easily able to do that. :sweat_smile:

**Comment by itinerare** [comment]
Good calls all around, I think-- and no worries, I'll be making a PR for stuff like this anyway so it's not much trouble. Thanks for doing the heavy lifting, haha!
