### ISSUE TITLE
Cannot admin transfer MYO to an alias.

### ISSUE THREAD

**Issue by preimpression** [corowne/lorekeeper#49]
**My version:** Modified-main on live site, does not include in-development branches. Mercury commented that this has happened for awhile so I believe this to be a Vanilla LK issue as well.

**Issue:**
I assume this will change anyway with the alias rework in V2.0.0 , but nevertheless - attempting to transfer a MYO slot to an Alias instead of a created account (such as to accommodate a DeviantArt username change) results in a failed transfer and a "Please enter a recipient for the transfer." message.

What's interesting is it works fine on fully-designed characters, just not in MYOs.

**Comment by itinerare** [comment]
Will review/fix as necessary for new alias storage system
