### ISSUE TITLE
Unable to verify using iCloud email

### ISSUE THREAD

**Issue by Citylites** [corowne/lorekeeper#590]
I've been seeing some users of a species I follow closely having trouble verifying their LK account because they're using iCloud. Is there any plans to fix this?

**Comment by itinerare** [comment]
This likely has less to do with LK itself and more with whatever service the species is using to send emails, as all LK does is send along instructions to whichever service to do so (and even this is via the underlying framework Laravel, so if there is an issue to fix in that regard it would be upstream). Unfortunately, this kind of thing is a known issue with e.g. Sendgrid, though I've not previously heard of it impacting iCloud addresses.

**Comment by Citylites** [comment]
Interesting, I'll forward this along to the staff. Thank you!
