### ISSUE TITLE
Image Hashing Command does not update database rows correctly

### ISSUE THREAD

**Issue by Ne-wt** [corowne/lorekeeper#751]
[View Here](https://github.com/corowne/lorekeeper/pull/749/files#diff-aa7510ea164127826e10f331935986573bf35faa19b33975ef21ea39a296422b)

doesn't update rows so the URLs are just 404s since the model is unaware of the new location

**Comment by Ne-wt** [comment]
was an incorrect merge by user |D

**Comment by itinerare** [comment]
Happens to the best of us....
