### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dotfloat** [corowne/lorekeeper#76]
Thanks for this project. I'd like to setup this for an ARPG but I'd like to know what the license of this project is. You can choose a license: https://choosealicense.com/

I tend to prefer GNU AGPLv3 since then network use is considered distribution, meaning that any forks of this projects must be kept FOSS.

**Comment by itinerare** [comment]
Hello! Thank you for your interest in the project.

We determined the MIT license to be best-suited to the project for a few reasons. Of course, we understand and support the sentiment of wanting improvements to be available to the community at large! Publicly available support from the community, either in the form of pull requests to this repo or optional [extensions](http://wiki.lorekeeper.me/index.php?title=Category:Extensions), are what have helped to make this project thrive, and we have done our best to foster an environment in which the community readily shares such works. However, not all improvements are appropriate or even practical to make publicly available-- given the circumstances of their creation, implementation of a feature or function being heavily tailored to a specific use case or project, etc. Moreover, many ARPGs are in a sense small businesses, and especially given this it would not be appropriate to demand that all parties be willing to reveal their source code.

We hope that clears things up for you! Let us know if you have any further questions.

**Comment by dotfloat** [comment]
That is perfectly acceptable thanks. I see that there's now a LICENSE file so I'm closing this issue. 🚀
